### ISSUE TITLE
Enabling additional plugins from Prism

### ISSUE THREAD

**Issue by bugrafelekoglu** [koca/vue-prism-editor#103]
I need to enable line-highlight plugin from Prism but I couldn't see a way to activate a plugin. Are there any way of this? Thank you.

**Comment by koca** [comment]
Unfortunatelly editor doesn't support prism plugins. You'll have to make ur own or use more advanced editors like monaco or codemirror.

**Comment by koca** [comment]
btw `vue-tut` package has line higlighting maybe this helps? https://github.com/evwt/vue-tut/blob/master/src/packages/TutorialHighlighter/TutorialHighlighter.vue

live demo: https://vn192.csb.app/
