### ISSUE TITLE
Using Markdown

### ISSUE THREAD

**Issue by jolo-dev** [koca/vue-prism-editor#104]
Hi,
is the editor Javascript only?
I have trouble using Markdown with it.
Basically, I replaced `js` with `markdown`:

```javascript
import 'prismjs/components/prism-markdown';
...
methods: {
      highlighter(code) {
        return highlight(code, languages.markdown); // languages.<insert language> to return html with markup
      },
    },
...
```

However, Javascript from the README seems to work.

**Comment by koca** [comment]
Hey! no, you can use all languages supported by prismjs.
