### ISSUE TITLE
fire focus event on editor using javascript

### ISSUE THREAD

**Issue by kangchals** [koca/vue-prism-editor#105]
Could you help me how to focus editor using javascript?

I set ref and check inner method but there is no methods to use.
I tried to fire .focus() or .click() on textarea or pre tag but it is not working.  (I tried them https://prism-editor.netlify.app/ on console)

Do you have any idea? Thank you!

**Comment by sadnub** [comment]
You can do this
```
methods:{
    focusTextArea() {
      const textarea = document.getElementsByClassName("prism-editor__textarea")[0];
      textarea.focus();
    },
}

and put a click handler on your vue-prism-editor 
```
@click="focusTextarea"
```

**Comment by kangchals** [comment]
Thank you for answering!

**Comment by koibi2** [comment]
点击空白后，光标定位到最后一行：
`    .prism-editor__container{
        height: 100%;
    }`
