### ISSUE TITLE
Not working without highlighter in 2.0.0-alpha.2

### ISSUE THREAD

**Issue by antja0** [koca/vue-prism-editor#106]
Version: 2.0.0-alpha.2

prism-editor component won't work at all without `:highlight` function prop assigned eg. like so `<prism-editor :highlight="highlighter"></prism-editor>`

To counter this I had to do this empty highlighter function in my code:
```js
  methods: {
    highlighter(code) {
      // Won't work with highlighter
      return code;
    },
  },
```

**Comment by SibeeshVenu** [comment]
@antja0  Have you already tried removing the `lang="ts"` in the `script` tag? I was facing this issue recently and it was because of the `lang='ts'`. I already answered the solution [here](https://stackoverflow.com/questions/66726731/could-not-find-a-declaration-file-for-module-prismjs-components-prism-core-vue/66726732#66726732). Hope it helps.

**Comment by koca** [comment]
hey @antja0, sorry but i don't understand your issue. You **have to** give a `highlight` prop as in docs. It doesn't work without highlight function.

**Comment by SibeeshVenu** [comment]
@koca From [this example](https://github.com/koca/vue-prism-editor/tree/feature/next#usage), if I add a` lang="ts"` in the `script` tag, that will always throw an error as ``` TS7016: Could not find a declaration file for module 'prismjs/components/prism-core'. '/node_modules/prismjs/components/prism-core.js' implicitly has an 'any' type.  Try `npm i --save-dev @types/prismjs` if it exists or add a new declaration (.d.ts) file containing `declare module 'prismjs/components/prism-core';` 

I think this is the issue @antja0  is mentioning here.

**Comment by antja0** [comment]
This threw an obscure error which caused me to waste my time.
If this is by design, then this issue is simply a suggestion to add a simple default value for this prop like `c => c`.

If you decide to keep it like this, then I'd suggest to make it more clear on the [npm page](https://www.npmjs.com/package/vue-prism-editor) (README) that this prop is required.
It currently only says that default value is "-" which really tells nothing. I assumed it would work with null.

**Comment by koca** [comment]
hey @SibeeshVenu, since v1 this library has nothing to do with `prismjs` package, so the error youre getting from `prismjs/components/prism-core` is not related to `vue-prism-editor`. Your issue is different from @antja0. As TS compiler suggests, you need to install types for prismjs.

**Comment by koca** [comment]
hey @antja0. Oh i see. I don't see the value of default function but we should improve the docs, you're right. Thanks.
