### ISSUE TITLE
Do not work with latest Vue 3

### ISSUE THREAD

**Issue by artfabrique** [koca/vue-prism-editor#123]
The setup was the same as in the instruction. I use webpack and typescript.
![image](https://user-images.githubusercontent.com/4455555/139325908-4362e421-0944-423a-9e58-22c472db37ac.png)

**Comment by DotoPototo** [comment]
Instead of sticking the `highlighter` function in `setup()`;
```js
setup() {
  const highlighter = (code) => {
    return highlight(code, languages.js)
  }
  return { highlighter };
},
```

Extract it to methods instead;
```js
setup() {
  // Your other setup stuff
},
methods: {
  highlighter(code) {
    return highlight(code, languages.js);
  },
},
```

**Comment by koca** [comment]
please provide an example using codesandbox or stackblitz. i will re-open the issue once you have the repro. :)
