### ISSUE TITLE
Add support for placeholder to documentation

### ISSUE THREAD

**Issue by devmount** [koca/vue-prism-editor#124]
Is there a possibility to maintain a placeholder text for the textarea?

I'm using this editor as form input for a textarea with syntax highlighting and it would be awesome to set the textarea placeholder attribute.

@koca I can create a PR if that would help.

**Comment by flohaider** [comment]
Could not find this anywhere in the documentation, but it looks like placeholder support is already in there.

 ```html
<prism-editor placeholder="Your placeholder text here"></prism-editor>
```

Tested with the latest version.

**Comment by devmount** [comment]
@flohaider Wow you're totally right. Seems like past-me never even tried the obvious 😂 Many thanks for pointing out!
@koca Maybe this should be added to the docs?

**Comment by koca** [comment]
Sure, we can add it to docs. Thanks for the report. :)
