### ISSUE TITLE
"we dont use `language-` classes anymore so thats why we need to add background and text color manually" - why?

### ISSUE THREAD

**Issue by seiyria** [koca/vue-prism-editor#134]
I'm trying to get this working, and honestly I'm at a loss. I have an editor, and the entire editor is too dark with the example code given. I saw this comment in the example, then looked at a Prism CSS file, and saw this:

```
code[class*="language-"],
pre[class*="language-"] {
	color: #f8f8f2;
	background: none;
	text-shadow: 0 1px rgba(0, 0, 0, 0.3);
	font-family: Consolas, Monaco, 'Andale Mono', 'Ubuntu Mono', monospace;
	font-size: 1em;
	text-align: left;
	white-space: pre;
	word-spacing: normal;
	word-break: normal;
	word-wrap: normal;
	line-height: 1.5;

	-moz-tab-size: 4;
	-o-tab-size: 4;
	tab-size: 4;

	-webkit-hyphens: none;
	-moz-hyphens: none;
	-ms-hyphens: none;
	hyphens: none;
}

/* Code blocks */
pre[class*="language-"] {
	padding: 1em;
	margin: .5em 0;
	overflow: auto;
	border-radius: 0.3em;
}
```

When I manually applied the `language-yaml` class to my `pre.prism-editor__editor` it works flawlessly. However, no matter what I do, even if I copy and paste these lines of CSS and rename them to work with that (no matter the specificity) they do not apply, leading me to have a black screen that just doesn't work, like so:

![image](https://user-images.githubusercontent.com/763609/153233117-e17fd083-53c6-469e-8f75-7aaeaa5c9ab9.png)

How do I work around this? Is there a way I can make this work with the current prismjs?

**Comment by seiyria** [comment]
okay, it looks like you can't do `<style scoped>` as it won't sufficiently overwrite the prism editor. hopefully this helps the next person who finds this!

**Comment by koca** [comment]
Glad you figured out. We should mention that in readme. Thanks for the report :)
