### ISSUE TITLE
Does not support other languages

### ISSUE THREAD

**Issue by xtan9** [koca/vue-prism-editor#14]
I tried language="sql". It does not work

**Comment by koca** [comment]
did you import the lang somewhere in your project? Don't know how you use prismjs but maybe sth like that:
```js
import "prismjs/components/prism-sql.js"
```

**Comment by xtan9** [comment]
https://codesandbox.io/s/61yrlnlnmn
It does not work in the demo also.

**Comment by koca** [comment]
It works if you import the sql lang file from prismjs.
add this line somewhere in `main.js` file.
```js
import "prismjs/components/prism-sql.js"
```

**Comment by xtan9** [comment]
Perfect. Thanks for the help!

**Comment by calebeaires** [comment]
I had the same problem. This issue help me to fix it. Woulb be great to put this tip on the readme.md page.

**Comment by NEK-RA** [comment]
Hi. One more question about this issue. I've got problem with "php" language.
Codesandbox — https://codesandbox.io/s/vue-prism-editor-php-raise-errors-2xuse
Problem: I've seen above the solution with SQL and checked it with PHP and JSON, so I included them into main.js:
```
import "prismjs/components/prism-php.js"
import "prismjs/components/prism-json.js"
```
When using language="json" everything works good. When I try to use language="php" these 7 problems are raised:

1. Error in getter for watcher "content": "TypeError: Cannot read property 'tokenizePlaceholders' of undefined"
2. Error in render: "TypeError: Cannot read property 'tokenizePlaceholders' of undefined"
3. Error in getter for watcher "content": "TypeError: Cannot read property 'tokenizePlaceholders' of undefined"
4. Error in render: "TypeError: Cannot read property 'tokenizePlaceholders' of undefined"
5. Error in mounted hook: "TypeError: Cannot read property 'innerHTML' of undefined"
6. Error in mounted hook: "TypeError: Cannot read property 'innerHTML' of undefined"
7. Error in nextTick: "TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'."

I've also decided to check for `prism` object, so I've imported it from 'prismjs' and checked for prism.languages — php exists in this object.
Any thoughts about that?

**Comment by yangyang-zhang** [comment]
> Hi. One more question about this issue. I've got problem with "php" language.
> Codesandbox — https://codesandbox.io/s/vue-prism-editor-php-raise-errors-2xuse
> Problem: I've seen above the solution with SQL and checked it with PHP and JSON, so I included them into main.js:
> 
> ```
> import "prismjs/components/prism-php.js"
> import "prismjs/components/prism-json.js"
> ```
> 
> When using language="json" everything works good. When I try to use language="php" these 7 problems are raised:
> 
> 1. Error in getter for watcher "content": "TypeError: Cannot read property 'tokenizePlaceholders' of undefined"
> 2. Error in render: "TypeError: Cannot read property 'tokenizePlaceholders' of undefined"
> 3. Error in getter for watcher "content": "TypeError: Cannot read property 'tokenizePlaceholders' of undefined"
> 4. Error in render: "TypeError: Cannot read property 'tokenizePlaceholders' of undefined"
> 5. Error in mounted hook: "TypeError: Cannot read property 'innerHTML' of undefined"
> 6. Error in mounted hook: "TypeError: Cannot read property 'innerHTML' of undefined"
> 7. Error in nextTick: "TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'."
> 
> I've also decided to check for `prism` object, so I've imported it from 'prismjs' and checked for prism.languages — php exists in this object.
> Any thoughts about that?

I have encountered the same problem. How did you solve it?

**Comment by koca** [comment]
Please upgrade to the new version v1.x

**Comment by rh78** [comment]
Hi I am on the newest version, and for CSS I get:

Error in nextTick: "TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'."

**Comment by valentinoli** [comment]
> Hi I am on the newest version, and for CSS I get:
> 
> Error in nextTick: "TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'."

I got a similar error and [this thread](https://github.com/koca/vue-prism-editor/issues/32) helped me
