### ISSUE TITLE
Auto resizing doesn't work with a computed property?

### ISSUE THREAD

**Issue by zantiu** [koca/vue-prism-editor#140]
When connecting v-model to a computed property instead of a property from data(), the automatic resizing doesn't work.

This is a code-sandbox showing the behavior: just try to add extra lines:

https://codesandbox.io/s/vue-prism-editor-example-forked-rdrch7?file=/src/App.vue

**Comment by zachinglis** [comment]
You were very close. You created a setter but didn't actually make it set.

If you make your setter: 
```js      
set(v) {
  this.code = v;
},
```

It works as intended.

**Comment by zantiu** [comment]
thanks!
