### ISSUE TITLE
support v-model

### ISSUE THREAD

**Issue by y-nk** [koca/vue-prism-editor#15]
Instead of `:code` and `@change`, could you support `v-model` by using `value` and `@input` ? or maybe `:code.sync` with `code` and `@update:code` ?

**Comment by koca** [comment]
You can still use v-model. Can you elaborate more on this? What's your use case?

**Comment by trickstival** [comment]
v-model works, but I still don't understand some points

why does the component use custom prop/event names?

if it used `:value/@input` it would get easier to implement transparent wrapper components. 

This is how I got here in the first place, cause I thought v-model wasn't being implemented, but my wrapper with `v-bind="$attrs"` didn't have the model custom option and was trying to pass `:value` prop to the editor child component.

Maybe it's a good idea to implement `.sync` modifier too, just like @y-nk said.

If you think my concerns are relevant and want some help with those or with implementing tests for them just let me know, I can help!

**Comment by koca** [comment]
If you want to help, sure. Send a pr :)
