### ISSUE TITLE
It breaks if initiated with null value

### ISSUE THREAD

**Issue by nikocraft** [koca/vue-prism-editor#17]
Error in getter for watcher "content": "TypeError: Cannot read property 'length' of null"

If I have a nullable css column in database and user does not input any css with first save, upon reloading the editor breaks because it tries to read the length of null. Can you fix this? I have a css field that user may or may not add some css to, the column is nullable, I can't force the user to enter css, and if they do not, your component breaks when they reload the page and data is read from the database.

found in
---> <PrismEditor> at Editor.vue

**Comment by koca** [comment]
Hi,
Thank you for the report.

You could just set the code to an empty string if the value is null.
like this:

```js
if(userCSSResponse === null){
  this.code = "";
}else{
  this.code = userCSSResponse;
}
```

that should do it

**Comment by nikocraft** [comment]
I wanted to avoid doing that, since it would make my code cleaner, but that is what I did to make it work :)

**Comment by nikocraft** [comment]
This is my app by the way:

https://www.youtube.com/watch?v=pCjZpwH88Z0

you are now going to be contributor indirectly to my project by me using this plugin :)

**Comment by koca** [comment]
I just watched the video your app looks really cool! 👍
Alright, tomorrow i'll look into it and i'll let you know :)

**Comment by nikocraft** [comment]
Great thanks for the consideration! :)

**Comment by koca** [comment]
Hey!
Just published a new version that should fix the issue :)

**Comment by nikocraft** [comment]
You are kicking ass man! Thank you for this quick job! I'll pull it in soon to verify it works and I can give it null :) Thank you again!

**Comment by nikocraft** [comment]
Hey you are in Turkey, right? What city? I'm in Alanya right now working on my CMS above. But I'm not Turkish :) Would you be interested in doing freelance for me in the future? If so let me know what you would cost per hour. You would get to work with me on the CMS you saw! :)

**Comment by nikocraft** [comment]
If interested to find more about the project, visit this: https://www.reddit.com/r/laraone

Once I launch I'll work to make that community bigger, currently circa 120 follow the project and it's not even released! :)

**Comment by koca** [comment]
Yep that's right I live in Ankara :) I'd like to chat if you could give me your telegram or whatsapp etc. shoot me an email imesutkoca@gmail.com

**Comment by nikocraft** [comment]
I've been to Ankara 10 years ago, cool I will send you the email now :)

**Comment by jefrydco** [comment]
> Just published a new version that should fix the issue :)

Hi @koca , I think this issue should be closed, isn't it?

**Comment by koca** [comment]
@jefrydco yep. Thanks for the fix! :)
