### ISSUE TITLE
Line and code aren't aligned

### ISSUE THREAD

**Issue by Tzahile** [koca/vue-prism-editor#18]
I copied the code exactly as shown in the example,
but adding lineNumbers option breaks the view:

![image](https://user-images.githubusercontent.com/13683050/56866398-49e7d900-69e1-11e9-81d6-c78af06c1220.png)

From code inspection, I noticed that the lineNumbers option adds a `<div>` which comes before the `<pre>` block.

I played with the styling a bit and adding `position: absolute;` to the `<div>` and some padding to the `<pre>` solved it.

I can do it in my css file (unless it is scoped), thought it'd be better if you could check what is the problem with what I experience :)

**Comment by koca** [comment]
Hey there,

Which example? I don't see any issues in the examples.

**Comment by Tzahile** [comment]
I meant the code shown in the `Usage` section

**Comment by Tzahile** [comment]
I meant the code that is shown in `Usage` section

**Comment by koca** [comment]
Yes there should be a div which comes before `pre` element. Are you sure that you included `VuePrismEditor.css` file?

**Comment by Tzahile** [comment]
At first I only imported the `import PrismEditor from "vue-prism-editor"` locally in the component.
Now I moved it to the `main.js` file with adding the css and it works.
Thanks! and cool tool :)

**Comment by koca** [comment]
You can use it in your components too. Just include the css and you're good to go ^^
