### ISSUE TITLE
Adding theme binding

### ISSUE THREAD

**Issue by Tzahile** [koca/vue-prism-editor#19]
Hi,

Can you please add option to set the theme of the editor?
Prismjs gives builtin themes as shown in their [site](https://prismjs.com),
can you add something like :theme="themes option" so that theme change is supported?

Thanks in advance

**Comment by koca** [comment]
Hi!
It's themable already. You can just import the theme you want. And it'll work.

**Comment by TheMaverickProgrammer** [comment]
@koca I think he means the ability to switch themes on-the-fly.

**Comment by Tzahile** [comment]
Indeed.
In my example, `:theme="themesOptions"` is a prop given dynamically to the component.

If you go to prismjs site, there's a `select` button that toggles all their themes, and changes style to what you choose.

**Comment by buryndin** [comment]
Not sure it can be easily implemented. Switching theme on prismjs site looks like a hack
https://github.com/PrismJS/prism/issues/643#issuecomment-123845033
Code from site:
```
setTheme = function (id) {
	var link = $$('link[href^="themes/prism"]')[0];

	link.href = themes.meta.path.replace(/\{id}/g, id);
	localStorage.setItem('theme', id);
};
```

**Comment by koca** [comment]
We don't support theming since you can use any highlighter you want. But you can do it yourself :). 
Released new version [v1](https://github.com/koca/vue-prism-editor/releases/tag/v1.0.1) 🎉
