### ISSUE TITLE
Break long lines

### ISSUE THREAD

**Issue by bernhardh** [koca/vue-prism-editor#22]
If the code is very long, without linebreak, it will exceed the line. Is there a way, to autobreak (word-break?) it?

Example:
https://codepen.io/anon/pen/MMabjY

The expected behavior would be:
![image](https://user-images.githubusercontent.com/642292/59457508-d2e39400-8e18-11e9-900c-5c7acea5cbb3.png)

**Comment by koca** [comment]
Did you fixed it? I don't see any issue here.

**Comment by koca** [comment]
Oh sorry you want support for `word wrap`. Not sure if we can support this anytime soon because we should also be thinking about the linenumbers etc.

**Comment by bernhardh** [comment]
I totally understand that. But as you can see, these long lines are really hard to read and its even harder to modify the code inside.

**Comment by koca** [comment]
I agree. But word wraps also makes the code hard to scan... You can't follow where's the line break, indentation etc. 
What's your use case? What kind of data you have? I mean you are having this issue just because you don't have enough space on mobile?

**Comment by bernhardh** [comment]
Sorry for late answer. The usecase is the following:

I am using a wysiwyg editor (tiptap) for editing website content. This editor (like most others) doesn't add linebreaks in the result HTML, which is stored into the database. 

I also want to edit this data as plain html, so I thought, I can use prism for it. But the problem is, that I have for example a 600 words long text plus html, without linebreak. So prism is useless in this situation, without word wrap.

**Comment by bernhardh** [comment]
Sry. for doublepost.

But please have a look at the example:

![image](https://user-images.githubusercontent.com/642292/64010594-5fe5e180-cb1a-11e9-95f4-017cb625b18b.png)

**Comment by tomgalpin** [comment]
I have the same question/issue.  
I was looking into trying to add this plugin:
https://prismjs.com/plugins/normalize-whitespace/

Do you have a recommendation on how to implement with vue-prism-editor?

**Comment by koca** [comment]
@tomgalpin we don't support prism plugins.
