### ISSUE TITLE
Does this allow for custom events?

### ISSUE THREAD

**Issue by rmccullagh** [koca/vue-prism-editor#24]
```
                    <vue-prism-editor
                        autocorrect="off"
                        autocapitalize="off"
                        spellcheck="false"
                        rows="8"
                        :code="model.content"
                        v-on:drop="onDrop($event)"
                        v-on:dragover="onDragOver($event)"
                        v-model="model.content"
                        :lineNumbers="false"
                        :autoStyleLineNumbers="false"
                        :emitEvents="true"
                        :language="'bash'"></vue-prism-editor>
```

Does vue-prism-editor allow for the v-on:drop attributes? I'm trying to attach an event to the contentEditable pre element, but this does not seem to work.

**Comment by koca** [comment]
Unfortunately no but we could. 
try to wrap prism-editor with a div and add events to that element. Let me know if it doesn't work.

**Comment by fdabek1** [comment]
> Unfortunately no but we could.
> try to wrap prism-editor with a div and add events to that element. Let me know if it doesn't work.

I am trying to get the blur event of the editor, but even putting one on the outside div doesn't work.  Any suggestions?

**Comment by koca** [comment]
I'll add blur and focus events in the next release.
In the meantime try to add `tabindex="0"` to the div on the outside of the editor. Because pure div doesn't have blur event. It should have `tabindex` or `contenteditable` attr.
