### ISSUE TITLE
Firefox version is broken

### ISSUE THREAD

**Issue by nikocraft** [koca/vue-prism-editor#28]
Hi are you aware that this component barly functions in Firefox, and it's exibiting strange behaviour. I'm using it for my CMS: https://www.youtube.com/watch?v=O-fO41eOp6o

Is there a chance you could take a look at this and see what's going crazy in FF? You can test it right in your demo links since the issue is there right when you start using it in FF.

**Comment by elevatebart** [comment]
Hey @nikocraft 

What version of Firefox are you using and what are the specs of your computer?
You might want to try disabling plugins as well to speed it up.
I just tried it out in FF and it purrs.

My config: 
Firefox 68.0.1 (64-bit) on windows 10 with a laptop of early 2015.

**Comment by nikocraft** [comment]
My config is 68.0 on windows 10, same page works in Chrome without any strange behaviour. See this video I just made for you on FF 68.0

https://www.youtube.com/watch?v=-jzH5_hfV-g

I had to press enter two times on line 1 to be able to go to line 2
On line 2 I pressed tab once only and cursort jumped now to line 3
These are just two weird things I found out, I'm sure there are more.

I'm not using any plugins on FF, it's a clean install. None of the behaviour seen in the video above happens in Chrome. 

All tested here: https://codesandbox.io/s/61yrlnlnmn

**Comment by elevatebart** [comment]
I reproduce easily in codesandbox indeed. 
I believe it either has to do with starting from an empty editor or to do with CodeSandbox since it is not happening [here](https://prism-editor.netlify.com/) at all.

I will have a quick look.

**Comment by koca** [comment]
@elevatebart agree. In codesandbox it behaves strange but as you mentioned seems ok.

**Comment by nikocraft** [comment]
I had exact same behaviour in my CMS, first youtube link in first post. I had to turn off the pluging completly in the CMS. Anyways why would sandbox work just fine in Chrome but not in FF, something is strange with FF version. I've had people complain to me that it was giving them problems in FF with my CMS, that's why I started to investigate it and since we could not fix it I turned it off in FF, but also reported it here for you in hopes you can fix it.

**Comment by elevatebart** [comment]
Have your users complained about non-empty editors?
I am simply trying to start somewhere for the fix.

Firefox is my main browser, I want to make sure it works for me ;-)

**Comment by nikocraft** [comment]
What is non-empty editor? In my CMs initially there is no code in prism-editor, users have to put it there, I believe I reported a bug for you about this before and you guys fixed it, see this:
https://github.com/koca/vue-prism-editor/issues/17

So do you guys think it's a problem if editor is initiated empty and FF starts to missbehave because of this?

**Comment by koca** [comment]
Released new version [v1](https://github.com/koca/vue-prism-editor/releases/tag/v1.0.1) 🎉
