### ISSUE TITLE
Error in nextTick: "ReferenceError: getComputedStyle is not defined"

### ISSUE THREAD

**Issue by 4ndre4s** [koca/vue-prism-editor#32]
I use the component in a Nuxt.js Application, but I get an error.

This is how the it gets rendered:
![grafik](https://user-images.githubusercontent.com/25303707/62681335-c5323100-b9b9-11e9-83ad-c15321eda3cc.png)

Error:
![grafik](https://user-images.githubusercontent.com/25303707/62681356-cf542f80-b9b9-11e9-83b9-5c20cac7063f.png)

Code:
![grafik](https://user-images.githubusercontent.com/25303707/62681465-0a566300-b9ba-11e9-8ba6-14994c0d2de6.png)

**Comment by astagi** [comment]
Hi @4ndre4s how did you fix this issue? I got the same error with Nuxt!

**Comment by 4ndre4s** [comment]
Hi, I also used nuxt. Actually I could not fix it :(

**Comment by astagi** [comment]
@4ndre4s  I found the root of the problem, you need to wrap the editor around <client-only>

```html
<client-only placeholder="Loading...">
  <prism-editor :code="code" language="js" :line-numbers="true" />
</client-only>
```

The error disappears from console log but the graphical issue remains. Maybe something related to the default css of Nuxt, I'll investigate further :)

Thanks for the quick reply!

**Comment by astagi** [comment]
Ok @4ndre4s I just fixed the second problem. We need to import `VuePrismEditor.css` as well to get the flex box for correctly displaying lines and code.

```js
import 'prismjs'
import 'prismjs/themes/prism-tomorrow.css'
import 'vue-prism-editor/dist/VuePrismEditor.css'

import PrismEditor from 'vue-prism-editor'
```

It works great!

**Comment by astagi** [comment]
Looks like there's also a PR open to fix this problem in documentation :) https://github.com/koca/vue-prism-editor/pull/36/files

**Comment by 4ndre4s** [comment]
Thank you!

**Comment by astagi** [comment]
YW

**Comment by koca** [comment]
Oh i should also add note for nuxt. Thanks guys!

**Comment by jordib123** [comment]
I have the same problem. However, the vue-prism-editor package only contains "prismeditor.min.css" and no "VuePrismEditor.css"... I am using version 1.3.0.

`TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.`

Edit: It looks like it only happens for php in
`return highlight(this.code, languages.php)`
Js, Ruby, Python, C#, ... works without issues.

**Comment by Fennec-hub** [comment]
@jordib123 take a look here #131, especially if you are using dynamic import.

**Comment by jordib123** [comment]
@Fennec-hub It looked like using php with Prism required an extra import besides prism-php

`import "prismjs/components/prism-markup-templating.js";`

**Comment by nicholasanthonys** [comment]
@4ndre4s  did you manage to solve the problem ?
