### ISSUE TITLE
Any similar projects?

### ISSUE THREAD

**Issue by trusktr** [koca/vue-prism-editor#33]
This is very cool!

I LOVE that this works on mobile due simply to contenteditable.

Are there any other efforts to make a contenteditable code editor that you know of?

(I see react-live is covering a textarea with a pre, which isn't quite the same.)

**Comment by koca** [comment]
Thanks :) glad you liked it ^^
Do i know any `code editors` that uses contenteditable? Nope. 
If you find any let me know :)
Cheers.

**Comment by trusktr** [comment]
I've been wanting a mobile-friendly HTML-based code editor for a long time now, but all of them (CodeMirror, Ace, VS Code Monaco, etc) do not work on mobile. They all have horrible issues that make editing on mobile useless.

I think this is the starting point for a new great HTML5 editor...

**Comment by koca** [comment]
You are right 💯%.
When i started to make this editor i  wanted to be simple and light weight code editor which also works on mobile. But i agree. we could do better ^^

**Comment by trusktr** [comment]
I seem to have found another one! If you try https://reactjs.org on mobile, the text editors for the demos work.

**Comment by trusktr** [comment]
The ones in the demos at https://svelte.dev/ want to work, but seem to have some glitchyness, like continually trying to focus the cursor (in Android Chrome).

**Comment by trusktr** [comment]
Ah, I see React's website is using LiveEditor from react-live.

**Comment by koca** [comment]
Btw react-live was doing the same thing as this editor. They were using contenteditable before textarea based solution. will check svelte^^

**Comment by koca** [comment]
I checked the editor on svelte.dev. its glichy can't delete something. Etc.
