### ISSUE TITLE
How can button insert '<img src="123">' in the cursor position 

### ISSUE THREAD

**Issue by cmdparkour** [koca/vue-prism-editor#34]
I have a button, I want to click it and it can insert some words like '<img src="xx">' in the cursor position, how can i do now

**Comment by koca** [comment]
Hi,
Unfortunatelly we don't support that.

**Comment by trusktr** [comment]
@cmdparkour That image seems to be broken. You want to insert code at the cursor position?

> Unfortunatelly we don't support that.

@koca But it is possible though, right? If so, shouldn't we keep this open as a feature request?

**Comment by koca** [comment]
@truskr It's possible. But i don't have time for it now :( but you're right 👍 we should keep this open.

**Comment by cmdparkour** [comment]
It's realizable, I know how to do it now.
I need to insert code at the cursor position when I click the button .
When I click the button , I have a event to do it , this event can call replaceSelection(str) and my code is insert at the cursor position.
`
// insert code at the cursor position
      insertCode(str) {
        this.$children[0].codemirror.replaceSelection(str)
      }
`

**Comment by jefrydco** [comment]
> @trusktr It's possible. But I don't have time for it now :( but you're right 👍 we should keep this open.

I think this could be contradicted with the idea of this package itself. In my opinion, this package exists to provide the simplest form of code editor. It is also stated in the readme section that this package is 

> A dead simple code editor with syntax highlighting and line numbers.

Supporting this will make the package more complicated.

**Comment by koca** [comment]
> Supporting this will make the package more complicated.

@jefrydco agree. But if someone find a simple solution we might consider merging.

(btw i edited your comment by mistake 😃)

**Comment by xinix** [comment]
Can you send the current caret position in any of the events? That way you can store that in your component, and handle the insert yourself.

**Comment by koca** [comment]
I don't think we will support this. so, closing.
