### ISSUE TITLE
Code highlight doesn't update unless a model is linked

### ISSUE THREAD

**Issue by Cerberus1746** [koca/vue-prism-editor#35]
Hello, I was testing this package and I found it quite interesting, however, I found a issue, which happens in the main demo too. If I update the code, aka, type a new one in the window, the new code won't have a new highlight. If I set a default code, it will have the highlight.

However, if I link it to a data model, the highlight works just fine. Below I gave some snippets.

Also, if that's expected, just ignore me :-P

Browser: Firefox 68.0.1
example code:
With this code the highlight doesn't work 
```javascript
Vue.use(BootstrapVue);
Vue.component("prism-editor", VuePrismEditor);

var default_app = new Vue({el: "#app"});
```
```html
<prism-editor emit-events line-numbers language="js"></prism-editor>
```

With this code, the highlight work just fine.
```javascript
Vue.use(BootstrapVue);
Vue.component("prism-editor", VuePrismEditor);

var default_app = new Vue({
    el: "#app",
    data: {
        code: ""
    }
});
```
```html
<prism-editor v-model="code" emit-events line-numbers language="js"></prism-editor>
```

Also, if you want a complete working code can be found in my package:
https://github.com/Cerberus1746/PandaCoreData/tree/development/panda_core_data/ui

**Comment by koca** [comment]
Hi thanks.
If you don't give a model what is the purpose of using it? Just trying to understand your use case.

**Comment by Cerberus1746** [comment]
Exactly! :V

But I took a while to realize what the issue was because I am a noob with vue. So I would suggest raising an exception if a model could not be found, and it was kinda weird because it was an error that was happening in the demo too.

**Comment by koca** [comment]
Alright maybe we'll do sth about it :) Cheers.

**Comment by trusktr** [comment]
Note! There's a point in not using the v-model, because there's a change event:

```vue
		<prism-editor
			v-model="___"
			:code="value"
			@change="handleChange"
			language="html"
			:lineNumbers="false"
		/>
```

S without `v-model`, it's still useful to use `@change`.
