### ISSUE TITLE
space between line numbers and code

### ISSUE THREAD

**Issue by trusktr** [koca/vue-prism-editor#37]
On mine there's no space:

<img width="445" alt="Screen Shot 2019-08-16 at 6 13 49 PM" src="https://user-images.githubusercontent.com/297678/63204925-05e11880-c052-11e9-9a1e-a753149c61b0.png">

Should there be spacing between the line numbers and the code? Or is this still TODO?

**Comment by trusktr** [comment]
Just curious, would the original Prism `line-numbers` plugin work? Or does that present issues when trying to update the highlight on code change?

**Comment by koca** [comment]
> Just curious, would the original Prism `line-numbers` plugin work? Or does that present issues when trying to update the highlight on code change?

Yes. Prism plugins causes errors. When the code changes we should also inform the plugins to re-render etc.

did you import the default styles? `.prism-editor__code` has `margin-left:8px` so there should be some space. If not you can add manually.

**Comment by trusktr** [comment]
I did do `import "vue-prism-editor/dist/VuePrismEditor.css"` in my code, but no spacing.

I ended up adding a style manually. 👍 Nice that the flexbox keeps everything in place!

**Comment by trusktr** [comment]
> When the code changes we should also inform the plugins to re-render etc.

Base on [this article](https://schier.co/blog/2013/01/07/how-to-re-run-prismjs-on-ajax-content.html) we can tell Prism to update by doing something like

```js
var block = document.getElementById('some-code')
Prism.highlightElement(block); // re-render?
```

Have you tried that approach?

**Comment by koca** [comment]
@trusktr hi, i have an issue with my macbook's display(needs to be repaired) :( but i will check the article on mobile.

**Comment by trusktr** [comment]
If it works, and it re-renders Prism line numbers, then it could eliminate the complexity from doing line numbers in vue-prism-editor.

**Comment by koca** [comment]
Released new version [v1](https://github.com/koca/vue-prism-editor/releases/tag/v1.0.1) 🎉
