### ISSUE TITLE
Clear editor history? 

### ISSUE THREAD

**Issue by clockworked247** [koca/vue-prism-editor#39]
Hi there, 

I use this library to render an editor in a single page app.  The editor renders code in a pop-up for editing.  On the first page load, Undo/Redo works fine, but if I close the pop-up and render a different piece of code the Undo history is there for my previous rendered code (causing an Undo to revert to the other codebase).  

So I'd like to know how I can programmatically clear the Undo/Redo history, so we get a new history for each rendering of the editor.

Thanks!

**Comment by koca** [comment]
We can do it on destroy but if you use editor inside keep-alive el than you should remove the history with a method or sth. If u'd like to contribute let me know(on destroy clear history) or I can do it later this week.

**Comment by clockworked247** [comment]
Thanks, I decided to switch to Codemirror.
