### ISSUE TITLE
Html entity 'greater then' auto inserts characters in the edited code

### ISSUE THREAD

**Issue by lvaneijden** [koca/vue-prism-editor#43]
It seems like when the editor is set to the HTML language, and you insert or even copy/paste a 'greater then' html entity in any form in there, the component also automatically injects new characters which is unintended behaviour.

Steps to reproduce:
- Open the editor on https://prism-editor.netlify.com/
- Enter a html entity for greater then: `&gt;`
- Keep typing characters behind it, you will see "> characters being inserted

**Comment by koca** [comment]
Hey! Im working on this issue and the next version of vue-prism-editor. So stay tuned.

**Comment by koca** [comment]
Released new version [v1](https://github.com/koca/vue-prism-editor/releases/tag/v1.0.1) 🎉
