### ISSUE TITLE
Prism is not defined

### ISSUE THREAD

**Issue by Tchoupinax** [koca/vue-prism-editor#45]
Hello,

i wanted to use your editor in my project but i have this error : `Prism is not defined`. I provide you a screenshot about the error:

![image](https://user-images.githubusercontent.com/9136206/67147175-c4a7f780-f292-11e9-9e04-01e76bcd10e9.png)

I'm using Nuxt.js (`"nuxt": "^2.10.1",`).

I followed your recommanded example :
```html
<template>
  <prism-editor :code="code" language="js"></prism-editor>
</template>

<script>
import PrismEditor from 'vue-prism-editor'
export default {
  components: {
    PrismEditor
  }
}
</script>
```
What i made wrong ?

Edit:

I thought it could be a ssr render error so i add `client-only` tags in my template and i also have the error client side :

![image](https://user-images.githubusercontent.com/9136206/67147231-72b3a180-f293-11e9-88cb-69833b0687f4.png)

Thank you :)

**Comment by Tchoupinax** [comment]
Ok, `prismjs` is neeeded... so i suggest to replace prism paragraph **before** talking about installing the project :)

**Comment by Tchoupinax** [comment]
PR has been created to answer to this issue (for next user :D)

**Comment by robitwtms** [comment]
I'm having this exact problem after following the documentation. What was the solution? I guess I could use a different method as per the documentation, but this is the recommended way of doing it.

**Comment by escael** [comment]
Hi i found this guide and it works perfectly for Nuxt
https://www.yasminzy.com/nuxt/prism.html

**Comment by Drabble** [comment]
I've run `npm install prismjs --save` and then imported prismjs in my component like so:

```
import "prismjs";
import "prismjs/themes/prism.css";
import PrismEditor from "vue-prism-editor";
```

**Comment by Tchoupinax** [comment]
Yeah it works but the issue is that the documentation is missing these intructions, #46 could improve that :)
