### ISSUE TITLE
Pressing space key between .token.punctuation shows &nbsp; [language="twig"]

### ISSUE THREAD

**Issue by 949mac** [koca/vue-prism-editor#49]
**Problem:**

When changing completed code in the editor, pressing the space key changes to `nbsp;`

If I just type from the beginning, there is no problem.... but if I edit something present, or stub out a placeholder, then the problem can be reproduced.

**Sample Implementation:**

`<prism-editor :code="advanced_statement" @change="handlePrismChange" language="twig"></prism-editor>`

**Visual:**
![image](https://media1.tenor.com/images/bd99e28d11b76af1dd9461ae4e7c639d/tenor.gif)

**Current Workaround:**

```
handlePrismChange(code) {
    this.advanced_statement = code.replace('&nbsp;', ' ');
}
```

**Comment by fenwick67** [comment]
Similar problem for jade/pug, sadly no workaround since literal `&nbsp;` is sometimes needed in jade templates :cry:

**Comment by koca** [comment]
Hey guys! Im working on this issue and the next version of vue-prism-editor. So stay tuned.

**Comment by 949mac** [comment]
Thank you, @koca! My experience has been solid otherwise.

Best Regards,

Mike

**Comment by 949mac** [comment]
Hi @koca, I'm curious -- how is this one coming?

Best Regards,

Mike

**Comment by koca** [comment]
Released new version [v1](https://github.com/koca/vue-prism-editor/releases/tag/v1.0.1) 🎉
