### ISSUE TITLE
Another text input on the same page loses focus

### ISSUE THREAD

**Issue by LightningLord** [koca/vue-prism-editor#63]
If I have a text input and prism editor on the same page, there are focus issues after entering text in prism editor. If I try to edit the text field, focus is forced back to prism editor after every keypress.

**Comment by juan-carvajal** [comment]
Same here, it happens also if you have two prism editor in the same component. Any fix known for this? Disabling events and changing editors event function did not work.

**Comment by Nektovet** [comment]
Same here, found a quick solution - just a little improvement for ` ./src/utils/selection-range.js`:

```
function position(el, pos) {
  if (document.activeElement !== el) return;
  //  the rest code goes here
```

**Comment by LightningLord** [comment]
@Nektovet totally works. Thanks!
