### ISSUE TITLE
Highlighting doesn't seem to work.

### ISSUE THREAD

**Issue by mewcrazy** [koca/vue-prism-editor#64]
Hello,

I'm loving the plugin. I instantly got PrismJS working in my vue project. Seems to work well with SSR too.

But I'm having trouble getting the highlighting to work. I added PrismJS, VuePrismEditor, and the css-files from both. I even tried different themes, they definitly getting loaded, but the highlighting stays off. Also the markup only shows me:
![image](https://user-images.githubusercontent.com/6299479/79695300-5d392780-8276-11ea-82e4-9c4a9e53842c.png)

I am able to switch the language, and the according classes are changing also. But not inside the <pre> - There it always says class="language-text".

Since I'm getting no errors which I could debug I'm a little helpless. Can you point me in the right direction?

Best wishes,
Dennis

**Comment by bartenew** [comment]
Same issue. Highlighting only works with "js" or "javascript" as the language. 

`<prism-editor language="adoc" v-model="body"></prism-editor>`
OR
`<prism-editor language="java" v-model="note.body"></prism-editor>`

renders it as text.

**Comment by bartenew** [comment]
I was able to figure it out. Just add
`import 'prismjs/components/prism-${lang}.min.js';`
to your imports.

In your case @mewcrazy 
`import 'prismjs/components/prism-php.min.js';`

**Comment by mewcrazy** [comment]
Doesn't seem to help in my case. Trying to include the file, but it always the error "Prism not defined". I use SSR, so maybe that's why.

**Comment by bartenew** [comment]
> Doesn't seem to help in my case. Trying to include the file, but it always the error "Prism not defined". I use SSR, so maybe that's why.

I get this error if I don't import 'prismjs' before 'prismjs/components/prism-asciidoc.min.js'; Did you try reordering imports?

**Comment by EgorGumin** [comment]
> import 'prismjs/components/prism-${lang}.min.js';

thank you, this import did the job for me. I think it's a good idea to include this in Readme

**Comment by koca** [comment]
Released new version [v1](https://github.com/koca/vue-prism-editor/releases/tag/v1.0.1) 🎉
Glad you guys figured out.
