### ISSUE TITLE
Editor adds two lines on enter

### ISSUE THREAD

**Issue by waleedhasank** [koca/vue-prism-editor#65]
I have been using this package with my Vue.TS application, I added a variable to my v-model, on pressing enter and then pressing backspace, instead of going to the previous state which should be "" in my variable, my variable now has 2 white-spaces with a line break, picture attached.

![Github_issue](https://user-images.githubusercontent.com/64019958/79758393-c84a3300-8336-11ea-94ad-95142eb966f2.PNG)

**Comment by koca** [comment]
Released new version [v1](https://github.com/koca/vue-prism-editor/releases/tag/v1.0.1) 🎉
