### ISSUE TITLE
Feature request: Format code

### ISSUE THREAD

**Issue by nwittwer** [koca/vue-prism-editor#67]
Hi, first of all great plugin! The [example](https://codesandbox.io/s/61yrlnlnmn) was really helpful for getting started.

I was curious if there's a way to trigger a code formatting action? When I paste code into a `vue-prism-editor` textarea, I'd like it to format the code, remove whitespace, etc. This would be similar to clicking "tidy" in Codepen or "format" in VSCode.

If this is outside the scope of the project, it would be great to be able to easily add plugins like [normalize-whitespace](https://prismjs.com/plugins/normalize-whitespace/). I know plugins are [not currently supported](https://github.com/koca/vue-prism-editor/issues/22#issuecomment-609953344).

**Comment by nwittwer** [comment]
Was able to get a simplified version, with a "tidy" button working using `js-beautify` (npm package).
Example: https://codesandbox.io/s/vue-prism-editor-beautify-example-sgyoc?file=/src/components/HelloWorld.vue

**Comment by koca** [comment]
Released new version [v1](https://github.com/koca/vue-prism-editor/releases/tag/v1.0.1) 🎉
