### ISSUE TITLE
Source Code for the Demo App on Netlify?

### ISSUE THREAD

**Issue by john-craft** [koca/vue-prism-editor#68]
Is the source code or the [demo app on Netlify](https://prism-editor.netlify.app/) available somewhere? It would be really helpful to see how the component is configured for the demo.

**Comment by wadewilliams** [comment]
https://github.com/koca/vue-prism-editor/blob/master/src/App.vue

**Comment by john-craft** [comment]
Don't know how I missed this. Thanks, @wadewilliams!
