### ISSUE TITLE
"Line numbers" breaks in production (Nuxt)

### ISSUE THREAD

**Issue by Woosy** [koca/vue-prism-editor#69]
Hi, I was running vue-prism-editor v0.5.1 with Nuxt (v2.12.2), and when I deployed my app (SSR mode, running both `nuxt build` and `nuxt start`), I noticed that the editor broke :
![image](https://user-images.githubusercontent.com/26418696/80317831-6b52ef00-8806-11ea-8be2-4dc41b80fc41.png)

However, when I'm in development mode (`nuxt`), it works just fine.
![image](https://user-images.githubusercontent.com/26418696/80317858-8de50800-8806-11ea-8091-002be2d39f23.png)

I updated to 0.6.1, and the issue is still the same.

**Comment by koca** [comment]
Do you use tailwind or `Purge CSS`? 
Released new version [v1](https://github.com/koca/vue-prism-editor/releases/tag/v1.0.1) 🎉

**Comment by koca** [comment]
Try wrapping with `ClientOnly` tag.
Made a nuxt example i hope this helps: https://codesandbox.io/s/nuxt-vue-prism-editor-62e06

**Comment by Woosy** [comment]
Oh, sorry I forgot about this issue! I managed to fix it a while ago.
Good guess! I was indeed using TailwindCSS and it was a PurgeCSS issue. An update of the @nuxtjs/tailwindcss module fixed my problem.

Thank you anyway, I will make sure to take a look at v1!
