### ISSUE TITLE
Syntax highlighting is not activated with prefilled code value

### ISSUE THREAD

**Issue by doubtx** [koca/vue-prism-editor#70]
Hello, I have an issue with syntax highlighting

Scenario 1: Load Component with preset value of "code"
The preset value highlighted correctly, but all the changes are no highlighted

Scenario 1: Load Component with  value of "code" of empty string or null
When null or empty string is set to the initial "code" - typing hew code get highlighted correctly

Please see the bug video:
https://d.pr/v/pTUlOT

Code to reproduce:
```html
<!doctype html>

<html lang="en">
<head>
    <meta charset="utf-8">

    <title>Vue editor debug</title>
    <meta name="description" content="The HTML5 Herald">
    <meta name="author" content="SitePoint">
    <!-- vue-prism-editor CSS -->
    <link rel="stylesheet" href="https://unpkg.com/vue-prism-editor/dist/VuePrismEditor.css">
    <link rel="stylesheet" href="https://unpkg.com/prismjs/themes/prism.css" />
</head>

<body>
<div id="app">
    <vue-prism-editor :code="code" language="js"></vue-prism-editor>
</div>
<!-- vue-prism-editor JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<script src="https://unpkg.com/prismjs"></script>
<script src="https://unpkg.com/vue-prism-editor"></script>


<!-- use -->
<script>
    Vue.component("vue-prism-editor", VuePrismEditor)
    new Vue({
        el: "#app",
        data: {
            code: "console.log('test')"
        }
    })
</script>
</body>
</html>
```

**Comment by koca** [comment]
Thank you for the report! Can you change `:code="code"` prop to `v-model="code"` or listen for `@change` event and set your `code` value manually for now. Will fix in next release.

**Comment by koca** [comment]
Released new version [v1](https://github.com/koca/vue-prism-editor/releases/tag/v1.0.1) 🎉
