### ISSUE TITLE
Error when using special html entity "&gt;"

### ISSUE THREAD

**Issue by DrMarkEy** [koca/vue-prism-editor#72]
When you enter & gt; (without the space) in an html-attribute inside the editor, inserting any other character anywhere into the editor will add the two characters "> before the & gt;. If you continue typing, more and more "> will be added. This can even be reproduced in the example at https://prism-editor.netlify.app/

**Comment by lvaneijden** [comment]
Just setting a reference point/duplicate here to same issue created some time ago, sadly no fix yet it seems :( https://github.com/koca/vue-prism-editor/issues/43

**Comment by koca** [comment]
Hey guys! Im working on this issue and the next version of vue-prism-editor. So stay tuned.

**Comment by koca** [comment]
Released new version [v1](https://github.com/koca/vue-prism-editor/releases/tag/v1.0.1) 🎉
