### ISSUE TITLE
Model doesn't update on cmd + x

### ISSUE THREAD

**Issue by vuhrmeister** [koca/vue-prism-editor#73]
If I cut marked text by pressing `cmd + x` the model does not get updated. Deleting the marked text by pressing backspace works though.

The code:
```
<prism-editor
  v-model="stylesModel"
  language="css"
/>
```

I'm using the latest version 0.6.1.

**Comment by koca** [comment]
Hey @vuhrmeister! Thanks for the report. I'll take a look and will let you know. ✌️

**Comment by koca** [comment]
Released new version [v1](https://github.com/koca/vue-prism-editor/releases/tag/v1.0.1) 🎉
