### ISSUE TITLE
Is it possible to bind Ctrl+Enter to something?

### ISSUE THREAD

**Issue by wsdookadr** [koca/vue-prism-editor#74]
Hi,

Is it possible through the current API to add a callback on a given key combination?
For example, since this is a code editor component `Ctrl+Enter` is very often used as a key
combination to run the code (in many applications).

Would [something like this](https://stackoverflow.com/a/2511474/827519) be possible in vue-prism-editor on vue-prism-editor's`keyup` event?

Thanks,
Stefan

UPDATE:

Apparently it's possible to do that via an attribute like this `v-on:keyup="keyUpHandler"` but in the handler, it looks like `e.preventDefault()` isn't enough to stop the `Enter` key from going through.

**Comment by koca** [comment]
Hi @wsdookadr! I'll see what i can do and i will let you know.

**Comment by koca** [comment]
Released new version [v1](https://github.com/koca/vue-prism-editor/releases/tag/v1.0.1) 🎉
Can you try and let me know if it works?

**Comment by phamcnm** [comment]
I recently tried and preventDefault() still doesn't seem to stop Enter from going through. Is it supposed to work yet or is there a work-around?
