### ISSUE TITLE
Number tokens are strangely styled

### ISSUE THREAD

**Issue by austinv11** [koca/vue-prism-editor#78]
For some reason when I insert a number literal there is a strange styling artifact that messes up line spacing and making the number look abnormally large. (Note the coy theme is active, but this occurs on the default theme as well).

![screenshot](https://i.imgur.com/vDgvlwI.png)

**Comment by austinv11** [comment]
It appears to be due to a styling conflict with buefy. My bad.

**Comment by namjals** [comment]
@austinv11 
How did you handle it?

**Comment by austinv11** [comment]
@namjals If I recall correctly, I ended up needing to copy and paste Prism CSS files and rename some things. Sorry, I don't quite remember the specific steps.

**Comment by namjals** [comment]
@austinv11 
my solution. thank you.

<style>
  .token.boolean,
  .token.number,
  .token.function {
    color: #f08d49;
    background-color: transparent;
    font-size: 1em;
    display: contents;
  }
</style>
