### ISSUE TITLE
Tab size should not be hardcoded

### ISSUE THREAD

**Issue by lane-c-wagner** [koca/vue-prism-editor#79]
It would be awesome if the tab character (currently hardcoded to 2 spaces) was configurable via props. I'm using this for Go code and I need actual tabs.

**Comment by koca** [comment]
Hey @lane-c-wagner, yes! and next version support this already. When i publish, you can use `tabSize` prop. Thanks!

If you wanna see the progress: #77

**Comment by lane-c-wagner** [comment]
Thanks!

**Comment by koca** [comment]
Released new version [v1](https://github.com/koca/vue-prism-editor/releases/tag/v1.0.1) 🎉
