### ISSUE TITLE
Can't focus on editor if value is ''

### ISSUE THREAD

**Issue by Pedrat** [koca/vue-prism-editor#80]
As title says, if the string value is '' i can't focus on the editor and edit whatever it has
However, if the value is for example '\n' i am able to focus and edit away 

Any information i can give i will gladly

**Comment by Pedrat** [comment]
The only thing i can do is press enter which produces an error on console terminal 
![image](https://user-images.githubusercontent.com/36329075/87562979-9b4bb900-c6b6-11ea-963c-e4d4c6ce12c4.png)

**Comment by koca** [comment]
hey, can you try the next version? 
here: #77

**Comment by Pedrat** [comment]
hey, thanks for the quick response!
yeah the next version works like a charm! it loses the default colour background that it had, is it supposed to?
thanks anyway! this is awesome

**Comment by Pedrat** [comment]
nevermind! saw your comment on the codesandbox!

**Comment by Pedrat** [comment]
that being said, how could we implement, let's say prism-solarizedlight in your editor? is there a simple way?

**Comment by koca** [comment]
Can you reproduce with codesandbox?

**Comment by Pedrat** [comment]
hm i was trying to reproduce it on codesandbox but i seem to be unable to import `import 'prismjs/components/prism-aql'` on codesandbox, even though i'm perfectly able to on my setup 

![image](https://user-images.githubusercontent.com/36329075/87657160-570df680-c752-11ea-9d44-d864743ba0ce.png)

Still, SQL is close enough and here it is, pay close attention to the AND and = (also same problem with <, >)
https://codesandbox.io/s/vue-prism-editor-next-cso39?file=/src/App.vue

**Comment by koca** [comment]
> hm i was trying to reproduce it on codesandbox but i seem to be unable to import `import 'prismjs/components/prism-aql'` on codesandbox, even though i'm perfectly able to on my setup
> 
> ![image](https://user-images.githubusercontent.com/36329075/87657160-570df680-c752-11ea-9d44-d864743ba0ce.png)
> 

file name is `prism-apl` but you are trying to import `prism-aql`.

> Still, SQL is close enough and here it is, pay close attention to the AND and = (also same problem with <, >)
> [codesandbox.io/s/vue-prism-editor-next-cso39?file=/src/App.vue](https://codesandbox.io/s/vue-prism-editor-next-cso39?file=/src/App.vue)

You've imported 2 prism styles. Remove the first one.

> 
> Also: are we not able to bind stuff to `code` now? only v-model?

Please read the readme. Yes its changed to `value`.

**Comment by koca** [comment]
Released new version [v1](https://github.com/koca/vue-prism-editor/releases/tag/v1.0.1) 🎉
