### ISSUE TITLE
Highlighting only work on v-model, :code will not work while editing

### ISSUE THREAD

**Issue by govo** [koca/vue-prism-editor#81]
while editing, v-model the highlighting works,
```
<prism-editor v-model="code"  language="js" ></prism-editor>
```

but with :code , will not work. (with :code only works on first load)
```
<prism-editor :code="code"  language="js" ></prism-editor>
```

**Comment by koca** [comment]
This is an expected behaviour.

btw Released new version [v1](https://github.com/koca/vue-prism-editor/releases/tag/v1.0.1) 🎉
