### ISSUE TITLE
vue-prism-editor:1 Uncaught ReferenceError: global is not defined 

### ISSUE THREAD

**Issue by krishna237409** [koca/vue-prism-editor#86]
Hi,
i am getting following error .
i am new to web development. can you please help to figure out the issue.

vue-prism-editor:1 Uncaught ReferenceError: global is not defined    at vue-prism-editor:1
i am using direct from browser.
<script src="https://unpkg.com/vue-prism-editor"></script>
Regards
Krishna

**Comment by koca** [comment]
Hey Krishna! Thanks for the report and i think there is an issue with TSDX build. I'll take a look later today.

**Comment by koca** [comment]
Hello @krishna237409! fixed and just released a new version! You can checkout the example on codepen: https://codepen.io/koca/pen/QVgqyR
Also updated the umd example on readme.

**Comment by Sandstedt** [comment]
Hi @koca

Having the same problem while using Vuepress v1.3.1 on the MoJS documentation website.

Tried out the alpha version, but instead got this error:
```
[Vue warn]: Failed to resolve async component: function () {
  return Promise.all(/*! import() */[__webpack_require__.e(54), __webpack_require__.e(6)]).then(__webpack_require__.bind(null, /*! ./docs/.vuepress/components/MojsInteractive */ "./docs/.vuepress/components/MojsInteractive.vue"));
}
Reason: TypeError: Object(...) is not a function
```

Implementation: https://github.com/mojs/mojs.github.io/blob/mojsinteractive-bugfix/docs/.vuepress/components/MojsInteractive.vue#L117

**Comment by Sandstedt** [comment]
I guess it has something with us upgrading from 0.5.1 to 1.2.2 recently. Will investigate further.

**Comment by koca** [comment]
Hey @Sandstedt thanks for the report 👍  i wanted to take a look but the link is broken(404). Can you send me a correct link?

**Comment by Sandstedt** [comment]
Sorry @koca, deleted the branch after downgrading to 0.6.2 (that works). Here's a working link of that implementation:
https://github.com/mojs/mojs.github.io/blob/source/docs/.vuepress/components/MojsInteractive.vue

**Comment by cory-weiner** [comment]
Is this resolved? I am still getting this error. Also using vuepress.

**Comment by dimaaan21** [comment]
Same problem with vite

vue-prism-editor - 1.2.2
vite - 2.6.14
