### ISSUE TITLE
Add documentation on how to highlight HTML

### ISSUE THREAD

**Issue by jannejava** [koca/vue-prism-editor#88]
Thanks for making this component!

However, I have a bit trouble of understanding on how to switch language to html from JavaScript in the examples.

I have read the you should use "markup" for XML-based code. But something along of this does not work;

```javascript
import { highlight, languages } from "prismjs/components/prism-core";
import "prismjs/components/prism-markup";
```

What am I doing wrong? Any hints or ideas appreciated!

**Comment by jannejava** [comment]
Never mind! Got it.

**Comment by koca** [comment]
Yep thats how you do it, Cool 👍
