### ISSUE TITLE
Why value option has disappeared?

### ISSUE THREAD

**Issue by Tchoupinax** [koca/vue-prism-editor#91]
Hello,

I noticed that before v1  there was a `value` option to give a string. Now, the only way to provide code is with a v-model. Why this option has disappeared ?

`v-model` is useful but in my case i would like to display read only code and several block in a same component. Without the avaibility to provide code as string, the logic becomes much more complicated.

How can we improve that ?

Thank you for your work

**Comment by BarnabasSzabolcs** [comment]
v-model="model" is short hand for :value="model" @input="model" so I think :value will still work.
