### ISSUE TITLE
Similar styling class names with Bulma library 

### ISSUE THREAD

**Issue by Mhdi-kr** [koca/vue-prism-editor#93]
I have used bulma css library in my projects and then I added this component to it. The colors were overridden and numbers would be in individual rounded divs with white background color which would mess the whole thing up ... after spending sometime on finding the root of problem I figured this component does not get along well with bulma library.

**Comment by Mhdi-kr** [comment]
I have found the solution.
I created a new sass file called `custom.bulma.sass` and loaded it globally on `main.js`
I looked for problematic classes in the bulma sass folder and isolated them by not importing them onto the custom sass file I created.
here's the exact imports which fixes the wrong colors and white rounded divs for numbers:
// bulma.custom.sass

```
@import "~bulma/sass/utilities/_all.sass"
@import "~bulma/sass/layout/_all.sass"
@import "~bulma/sass/helpers/_all.sass"
@import "~bulma/sass/grid/_all.sass"
@import "~bulma/sass/form/_all.sass"
@import "~bulma/sass/elements/box.sass"
@import "~bulma/sass/elements/button.sass"
@import "~bulma/sass/elements/container.sass"
@import "~bulma/sass/elements/content.sass"
@import "~bulma/sass/elements/form.sass"
@import "~bulma/sass/elements/icon.sass"
@import "~bulma/sass/elements/image.sass"
@import "~bulma/sass/elements/notification.sass"
@import "~bulma/sass/elements/progress.sass"
@import "~bulma/sass/elements/table.sass"
@import "~bulma/sass/elements/tag.sass"
@import "~bulma/sass/elements/title.sass"
@import "~bulma/sass/components/_all.sass"
@import "~bulma/sass/base/helpers.sass"
@import "~bulma/sass/base/minireset.sass"

```

**Comment by johangit** [comment]
@koca I have the same problem. Maybe the better way is to use scoped styles for editor? Or class names with prefixes (`.prism-number` instead `.number`)?

**Comment by koca** [comment]
> @koca I have the same problem. Maybe the better way is to use scoped styles for editor? Or class names with prefixes (`.prism-number` instead `.number`)?

we don't a have class called `.number` its coming from `prismjs`. There is nothing we can do.
our classes are already prefixed with `prism-editor`. you can see all classnames there: https://github.com/koca/vue-prism-editor/blob/master/packages/vue-prism-editor/src/styles.css

**Comment by tansaku** [comment]
@Mhdi-kr I'm having the exact same problem in my project, however I don't currently have any sass files or a main.js so I'm unclear where to put bulma.custom.sass in my nuxt project...

I tried adding the following to `nuxt.config.js`

```
  // Global CSS: https://go.nuxtjs.dev/config-css
  css: [
    '@assets/sass/bulma.custom.sass',
  ],
```

with the file you mention in that location, but it doesn't seem to have helped.  I guess this is a nuxt specific issue that I'll have to dig into, but if anyone has any ideas I am all ears :-)

**Comment by tansaku** [comment]
@koa should prismjs be making a change?

**Comment by vmartins** [comment]
My solution:
- install [```babel-plugin-prismjs```](https://github.com/mAAdhaTTah/babel-plugin-prismjs)
```
npm install --save-dev babel-plugin-prismjs
```

- in your ```.babelrc``` or ```babel.config.js```, register the plugin [Custom Class](https://prismjs.com/plugins/custom-class/)
```js
// my babel.config.js
module.exports = {
  presets: [
    '@vue/cli-plugin-babel/preset'
  ],
  plugins: [
    ["prismjs", {
      "plugins": ["custom-class"],
    }]
  ]
}
```
- replace prism classes
```js
...

import { highlight, languages, plugins } from 'prismjs/components/prism-core'
import 'prismjs/plugins/custom-class/prism-custom-class'

...

    methods: {
        highlighter(code) {
            plugins.customClass.map({
                tag: 'prism-tag',
            })
            return highlight(code, languages.js)
        }
    }

...
```

- add your custom css
```css
.prism-tag {
    color: #905;
}
```
