### ISSUE TITLE
Diff Highlight Usage

### ISSUE THREAD

**Issue by akbarnafisa** [koca/vue-prism-editor#94]
Is there any documentation on how to use Diff highlights on JS? I've tried to use `diff-javascript` but it ends up using `language-text`

`diff-javascript`
```diff-javascript
-    let foo = bar.baz([1, 2, 3]);
+    const foo = bar.baz([1, 2, 3]) + 1;
```

![image](https://user-images.githubusercontent.com/16829122/95671674-f7de4780-0bc3-11eb-9fcb-940357b62551.png)

**Comment by koca** [comment]
As stated in the readme, unfortunatelly we don't support prismjs plugins but you can do it yourself. with custom highlighter function.
