### ISSUE TITLE
autocomplete feature

### ISSUE THREAD

**Issue by ozanh** [koca/vue-prism-editor#98]
Selam Mesut,

Thank you for the library. I started to use it in my script language's [playground](https://play.verigraf.com). I wonder if you plan to add auto complete feature in the near future. Let me know if you have such a plan.

**Comment by koca** [comment]
Selam Ozan,

Thanks :) it's a good idea but i don't think i will be adding this feature in the near future. I'd like to keep this project simple and light weight as much as possible so you know... Your script language seems cool btw :)

**Comment by ozanh** [comment]
Thanks Mesut :smiley: 
It is a nice to have feature for me now so I can wait.
Best.

**Comment by zhoufanglu** [comment]
Has this demand been cut at present?
